### ISSUE TITLE
Spelling error in Readme.md

### ISSUE THREAD

**Issue by pidgey0403** [mirceaulinic/alerta-blackout-regex#19]
In the second paragraph under the 'Important' section, the spelling for the word ``setup`` is incorrect.

Current behaviour: 
``To fine tune this behaviour for your own setuo [...] ``
Desired behaviour: 
``To fine tune this behaviour for your own setup [...]``

**Comment by mirceaulinic** [comment]
Thanks for the fix @natcoso9955!
